[project]
name = "monitoring-snapmirror-relationship-health"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aws-lambda-powertools>=3.3.0",
    "boto3>=1.35.68",
    "netapp-ontap>=9.16.1.0",
]
